dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    version: "0.6.8"
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
dotenv: .env
networks:
    development:
      cmd_settings:
        default_balance: 100000000